#!/usr/bin/env python3
import random
import os
import export_quotes 


def random_line(file):
    line = next(file)
    
    for num, xline in enumerate(file, 2):
        if random.randrange(num):
            continue
        line = xline.strip()
    
    return line

with open(f'{export_quotes.CDIR}/quotes.txt', 'r') as quote_file:
    print(random_line(quote_file))
